/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InformationGroupImport } from './routes/informationGroup'
import { Route as GalleryImport } from './routes/gallery'
import { Route as EtcImport } from './routes/etc'
import { Route as BookInformationGroupImport } from './routes/bookInformationGroup'
import { Route as IndexImport } from './routes/index'
import { Route as InformationGroupWelcomeMessageImport } from './routes/informationGroup.welcomeMessage'
import { Route as InformationGroupPromotionImport } from './routes/informationGroup.promotion'
import { Route as InformationGroupNoticeImport } from './routes/informationGroup.notice'
import { Route as InformationGroupLivingImport } from './routes/informationGroup.living'
import { Route as InformationGroupInformationImport } from './routes/informationGroup.information'
import { Route as InformationGroupFacilityImport } from './routes/informationGroup.facility'
import { Route as InformationGroupEventImport } from './routes/informationGroup.event'
import { Route as GalleryDigitalGalleryImport } from './routes/gallery.digitalGallery'
import { Route as EtcReturnImport } from './routes/etc.return'
import { Route as EtcLineImport } from './routes/etc.line'
import { Route as EtcCourseRegistrationImport } from './routes/etc.courseRegistration'
import { Route as EtcCourseListImport } from './routes/etc.courseList'
import { Route as BookInformationGroupNewImport } from './routes/bookInformationGroup.new'
import { Route as BookInformationGroupLibrarianImport } from './routes/bookInformationGroup.librarian'
import { Route as BookInformationGroupDetailImport } from './routes/bookInformationGroup.detail'
import { Route as BookInformationGroupCustomImport } from './routes/bookInformationGroup.custom'
import { Route as BookInformationGroupChartImport } from './routes/bookInformationGroup.chart'
import { Route as BookInformationGroupBigdataImport } from './routes/bookInformationGroup.bigdata'
import { Route as BookInformationGroupBestImport } from './routes/bookInformationGroup.best'

// Create/Update Routes

const InformationGroupRoute = InformationGroupImport.update({
  id: '/informationGroup',
  path: '/informationGroup',
  getParentRoute: () => rootRoute,
} as any)

const GalleryRoute = GalleryImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRoute,
} as any)

const EtcRoute = EtcImport.update({
  id: '/etc',
  path: '/etc',
  getParentRoute: () => rootRoute,
} as any)

const BookInformationGroupRoute = BookInformationGroupImport.update({
  id: '/bookInformationGroup',
  path: '/bookInformationGroup',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InformationGroupWelcomeMessageRoute =
  InformationGroupWelcomeMessageImport.update({
    id: '/welcomeMessage',
    path: '/welcomeMessage',
    getParentRoute: () => InformationGroupRoute,
  } as any)

const InformationGroupPromotionRoute = InformationGroupPromotionImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => InformationGroupRoute,
} as any)

const InformationGroupNoticeRoute = InformationGroupNoticeImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => InformationGroupRoute,
} as any)

const InformationGroupLivingRoute = InformationGroupLivingImport.update({
  id: '/living',
  path: '/living',
  getParentRoute: () => InformationGroupRoute,
} as any)

const InformationGroupInformationRoute =
  InformationGroupInformationImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => InformationGroupRoute,
  } as any)

const InformationGroupFacilityRoute = InformationGroupFacilityImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => InformationGroupRoute,
} as any)

const InformationGroupEventRoute = InformationGroupEventImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => InformationGroupRoute,
} as any)

const GalleryDigitalGalleryRoute = GalleryDigitalGalleryImport.update({
  id: '/digitalGallery',
  path: '/digitalGallery',
  getParentRoute: () => GalleryRoute,
} as any)

const EtcReturnRoute = EtcReturnImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => EtcRoute,
} as any)

const EtcLineRoute = EtcLineImport.update({
  id: '/line',
  path: '/line',
  getParentRoute: () => EtcRoute,
} as any)

const EtcCourseRegistrationRoute = EtcCourseRegistrationImport.update({
  id: '/courseRegistration',
  path: '/courseRegistration',
  getParentRoute: () => EtcRoute,
} as any)

const EtcCourseListRoute = EtcCourseListImport.update({
  id: '/courseList',
  path: '/courseList',
  getParentRoute: () => EtcRoute,
} as any)

const BookInformationGroupNewRoute = BookInformationGroupNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BookInformationGroupRoute,
} as any)

const BookInformationGroupLibrarianRoute =
  BookInformationGroupLibrarianImport.update({
    id: '/librarian',
    path: '/librarian',
    getParentRoute: () => BookInformationGroupRoute,
  } as any)

const BookInformationGroupDetailRoute = BookInformationGroupDetailImport.update(
  {
    id: '/detail',
    path: '/detail',
    getParentRoute: () => BookInformationGroupRoute,
  } as any,
)

const BookInformationGroupCustomRoute = BookInformationGroupCustomImport.update(
  {
    id: '/custom',
    path: '/custom',
    getParentRoute: () => BookInformationGroupRoute,
  } as any,
)

const BookInformationGroupChartRoute = BookInformationGroupChartImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => BookInformationGroupRoute,
} as any)

const BookInformationGroupBigdataRoute =
  BookInformationGroupBigdataImport.update({
    id: '/bigdata',
    path: '/bigdata',
    getParentRoute: () => BookInformationGroupRoute,
  } as any)

const BookInformationGroupBestRoute = BookInformationGroupBestImport.update({
  id: '/best',
  path: '/best',
  getParentRoute: () => BookInformationGroupRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bookInformationGroup': {
      id: '/bookInformationGroup'
      path: '/bookInformationGroup'
      fullPath: '/bookInformationGroup'
      preLoaderRoute: typeof BookInformationGroupImport
      parentRoute: typeof rootRoute
    }
    '/etc': {
      id: '/etc'
      path: '/etc'
      fullPath: '/etc'
      preLoaderRoute: typeof EtcImport
      parentRoute: typeof rootRoute
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryImport
      parentRoute: typeof rootRoute
    }
    '/informationGroup': {
      id: '/informationGroup'
      path: '/informationGroup'
      fullPath: '/informationGroup'
      preLoaderRoute: typeof InformationGroupImport
      parentRoute: typeof rootRoute
    }
    '/bookInformationGroup/best': {
      id: '/bookInformationGroup/best'
      path: '/best'
      fullPath: '/bookInformationGroup/best'
      preLoaderRoute: typeof BookInformationGroupBestImport
      parentRoute: typeof BookInformationGroupImport
    }
    '/bookInformationGroup/bigdata': {
      id: '/bookInformationGroup/bigdata'
      path: '/bigdata'
      fullPath: '/bookInformationGroup/bigdata'
      preLoaderRoute: typeof BookInformationGroupBigdataImport
      parentRoute: typeof BookInformationGroupImport
    }
    '/bookInformationGroup/chart': {
      id: '/bookInformationGroup/chart'
      path: '/chart'
      fullPath: '/bookInformationGroup/chart'
      preLoaderRoute: typeof BookInformationGroupChartImport
      parentRoute: typeof BookInformationGroupImport
    }
    '/bookInformationGroup/custom': {
      id: '/bookInformationGroup/custom'
      path: '/custom'
      fullPath: '/bookInformationGroup/custom'
      preLoaderRoute: typeof BookInformationGroupCustomImport
      parentRoute: typeof BookInformationGroupImport
    }
    '/bookInformationGroup/detail': {
      id: '/bookInformationGroup/detail'
      path: '/detail'
      fullPath: '/bookInformationGroup/detail'
      preLoaderRoute: typeof BookInformationGroupDetailImport
      parentRoute: typeof BookInformationGroupImport
    }
    '/bookInformationGroup/librarian': {
      id: '/bookInformationGroup/librarian'
      path: '/librarian'
      fullPath: '/bookInformationGroup/librarian'
      preLoaderRoute: typeof BookInformationGroupLibrarianImport
      parentRoute: typeof BookInformationGroupImport
    }
    '/bookInformationGroup/new': {
      id: '/bookInformationGroup/new'
      path: '/new'
      fullPath: '/bookInformationGroup/new'
      preLoaderRoute: typeof BookInformationGroupNewImport
      parentRoute: typeof BookInformationGroupImport
    }
    '/etc/courseList': {
      id: '/etc/courseList'
      path: '/courseList'
      fullPath: '/etc/courseList'
      preLoaderRoute: typeof EtcCourseListImport
      parentRoute: typeof EtcImport
    }
    '/etc/courseRegistration': {
      id: '/etc/courseRegistration'
      path: '/courseRegistration'
      fullPath: '/etc/courseRegistration'
      preLoaderRoute: typeof EtcCourseRegistrationImport
      parentRoute: typeof EtcImport
    }
    '/etc/line': {
      id: '/etc/line'
      path: '/line'
      fullPath: '/etc/line'
      preLoaderRoute: typeof EtcLineImport
      parentRoute: typeof EtcImport
    }
    '/etc/return': {
      id: '/etc/return'
      path: '/return'
      fullPath: '/etc/return'
      preLoaderRoute: typeof EtcReturnImport
      parentRoute: typeof EtcImport
    }
    '/gallery/digitalGallery': {
      id: '/gallery/digitalGallery'
      path: '/digitalGallery'
      fullPath: '/gallery/digitalGallery'
      preLoaderRoute: typeof GalleryDigitalGalleryImport
      parentRoute: typeof GalleryImport
    }
    '/informationGroup/event': {
      id: '/informationGroup/event'
      path: '/event'
      fullPath: '/informationGroup/event'
      preLoaderRoute: typeof InformationGroupEventImport
      parentRoute: typeof InformationGroupImport
    }
    '/informationGroup/facility': {
      id: '/informationGroup/facility'
      path: '/facility'
      fullPath: '/informationGroup/facility'
      preLoaderRoute: typeof InformationGroupFacilityImport
      parentRoute: typeof InformationGroupImport
    }
    '/informationGroup/information': {
      id: '/informationGroup/information'
      path: '/information'
      fullPath: '/informationGroup/information'
      preLoaderRoute: typeof InformationGroupInformationImport
      parentRoute: typeof InformationGroupImport
    }
    '/informationGroup/living': {
      id: '/informationGroup/living'
      path: '/living'
      fullPath: '/informationGroup/living'
      preLoaderRoute: typeof InformationGroupLivingImport
      parentRoute: typeof InformationGroupImport
    }
    '/informationGroup/notice': {
      id: '/informationGroup/notice'
      path: '/notice'
      fullPath: '/informationGroup/notice'
      preLoaderRoute: typeof InformationGroupNoticeImport
      parentRoute: typeof InformationGroupImport
    }
    '/informationGroup/promotion': {
      id: '/informationGroup/promotion'
      path: '/promotion'
      fullPath: '/informationGroup/promotion'
      preLoaderRoute: typeof InformationGroupPromotionImport
      parentRoute: typeof InformationGroupImport
    }
    '/informationGroup/welcomeMessage': {
      id: '/informationGroup/welcomeMessage'
      path: '/welcomeMessage'
      fullPath: '/informationGroup/welcomeMessage'
      preLoaderRoute: typeof InformationGroupWelcomeMessageImport
      parentRoute: typeof InformationGroupImport
    }
  }
}

// Create and export the route tree

interface BookInformationGroupRouteChildren {
  BookInformationGroupBestRoute: typeof BookInformationGroupBestRoute
  BookInformationGroupBigdataRoute: typeof BookInformationGroupBigdataRoute
  BookInformationGroupChartRoute: typeof BookInformationGroupChartRoute
  BookInformationGroupCustomRoute: typeof BookInformationGroupCustomRoute
  BookInformationGroupDetailRoute: typeof BookInformationGroupDetailRoute
  BookInformationGroupLibrarianRoute: typeof BookInformationGroupLibrarianRoute
  BookInformationGroupNewRoute: typeof BookInformationGroupNewRoute
}

const BookInformationGroupRouteChildren: BookInformationGroupRouteChildren = {
  BookInformationGroupBestRoute: BookInformationGroupBestRoute,
  BookInformationGroupBigdataRoute: BookInformationGroupBigdataRoute,
  BookInformationGroupChartRoute: BookInformationGroupChartRoute,
  BookInformationGroupCustomRoute: BookInformationGroupCustomRoute,
  BookInformationGroupDetailRoute: BookInformationGroupDetailRoute,
  BookInformationGroupLibrarianRoute: BookInformationGroupLibrarianRoute,
  BookInformationGroupNewRoute: BookInformationGroupNewRoute,
}

const BookInformationGroupRouteWithChildren =
  BookInformationGroupRoute._addFileChildren(BookInformationGroupRouteChildren)

interface EtcRouteChildren {
  EtcCourseListRoute: typeof EtcCourseListRoute
  EtcCourseRegistrationRoute: typeof EtcCourseRegistrationRoute
  EtcLineRoute: typeof EtcLineRoute
  EtcReturnRoute: typeof EtcReturnRoute
}

const EtcRouteChildren: EtcRouteChildren = {
  EtcCourseListRoute: EtcCourseListRoute,
  EtcCourseRegistrationRoute: EtcCourseRegistrationRoute,
  EtcLineRoute: EtcLineRoute,
  EtcReturnRoute: EtcReturnRoute,
}

const EtcRouteWithChildren = EtcRoute._addFileChildren(EtcRouteChildren)

interface GalleryRouteChildren {
  GalleryDigitalGalleryRoute: typeof GalleryDigitalGalleryRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryDigitalGalleryRoute: GalleryDigitalGalleryRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface InformationGroupRouteChildren {
  InformationGroupEventRoute: typeof InformationGroupEventRoute
  InformationGroupFacilityRoute: typeof InformationGroupFacilityRoute
  InformationGroupInformationRoute: typeof InformationGroupInformationRoute
  InformationGroupLivingRoute: typeof InformationGroupLivingRoute
  InformationGroupNoticeRoute: typeof InformationGroupNoticeRoute
  InformationGroupPromotionRoute: typeof InformationGroupPromotionRoute
  InformationGroupWelcomeMessageRoute: typeof InformationGroupWelcomeMessageRoute
}

const InformationGroupRouteChildren: InformationGroupRouteChildren = {
  InformationGroupEventRoute: InformationGroupEventRoute,
  InformationGroupFacilityRoute: InformationGroupFacilityRoute,
  InformationGroupInformationRoute: InformationGroupInformationRoute,
  InformationGroupLivingRoute: InformationGroupLivingRoute,
  InformationGroupNoticeRoute: InformationGroupNoticeRoute,
  InformationGroupPromotionRoute: InformationGroupPromotionRoute,
  InformationGroupWelcomeMessageRoute: InformationGroupWelcomeMessageRoute,
}

const InformationGroupRouteWithChildren =
  InformationGroupRoute._addFileChildren(InformationGroupRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookInformationGroup': typeof BookInformationGroupRouteWithChildren
  '/etc': typeof EtcRouteWithChildren
  '/gallery': typeof GalleryRouteWithChildren
  '/informationGroup': typeof InformationGroupRouteWithChildren
  '/bookInformationGroup/best': typeof BookInformationGroupBestRoute
  '/bookInformationGroup/bigdata': typeof BookInformationGroupBigdataRoute
  '/bookInformationGroup/chart': typeof BookInformationGroupChartRoute
  '/bookInformationGroup/custom': typeof BookInformationGroupCustomRoute
  '/bookInformationGroup/detail': typeof BookInformationGroupDetailRoute
  '/bookInformationGroup/librarian': typeof BookInformationGroupLibrarianRoute
  '/bookInformationGroup/new': typeof BookInformationGroupNewRoute
  '/etc/courseList': typeof EtcCourseListRoute
  '/etc/courseRegistration': typeof EtcCourseRegistrationRoute
  '/etc/line': typeof EtcLineRoute
  '/etc/return': typeof EtcReturnRoute
  '/gallery/digitalGallery': typeof GalleryDigitalGalleryRoute
  '/informationGroup/event': typeof InformationGroupEventRoute
  '/informationGroup/facility': typeof InformationGroupFacilityRoute
  '/informationGroup/information': typeof InformationGroupInformationRoute
  '/informationGroup/living': typeof InformationGroupLivingRoute
  '/informationGroup/notice': typeof InformationGroupNoticeRoute
  '/informationGroup/promotion': typeof InformationGroupPromotionRoute
  '/informationGroup/welcomeMessage': typeof InformationGroupWelcomeMessageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookInformationGroup': typeof BookInformationGroupRouteWithChildren
  '/etc': typeof EtcRouteWithChildren
  '/gallery': typeof GalleryRouteWithChildren
  '/informationGroup': typeof InformationGroupRouteWithChildren
  '/bookInformationGroup/best': typeof BookInformationGroupBestRoute
  '/bookInformationGroup/bigdata': typeof BookInformationGroupBigdataRoute
  '/bookInformationGroup/chart': typeof BookInformationGroupChartRoute
  '/bookInformationGroup/custom': typeof BookInformationGroupCustomRoute
  '/bookInformationGroup/detail': typeof BookInformationGroupDetailRoute
  '/bookInformationGroup/librarian': typeof BookInformationGroupLibrarianRoute
  '/bookInformationGroup/new': typeof BookInformationGroupNewRoute
  '/etc/courseList': typeof EtcCourseListRoute
  '/etc/courseRegistration': typeof EtcCourseRegistrationRoute
  '/etc/line': typeof EtcLineRoute
  '/etc/return': typeof EtcReturnRoute
  '/gallery/digitalGallery': typeof GalleryDigitalGalleryRoute
  '/informationGroup/event': typeof InformationGroupEventRoute
  '/informationGroup/facility': typeof InformationGroupFacilityRoute
  '/informationGroup/information': typeof InformationGroupInformationRoute
  '/informationGroup/living': typeof InformationGroupLivingRoute
  '/informationGroup/notice': typeof InformationGroupNoticeRoute
  '/informationGroup/promotion': typeof InformationGroupPromotionRoute
  '/informationGroup/welcomeMessage': typeof InformationGroupWelcomeMessageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bookInformationGroup': typeof BookInformationGroupRouteWithChildren
  '/etc': typeof EtcRouteWithChildren
  '/gallery': typeof GalleryRouteWithChildren
  '/informationGroup': typeof InformationGroupRouteWithChildren
  '/bookInformationGroup/best': typeof BookInformationGroupBestRoute
  '/bookInformationGroup/bigdata': typeof BookInformationGroupBigdataRoute
  '/bookInformationGroup/chart': typeof BookInformationGroupChartRoute
  '/bookInformationGroup/custom': typeof BookInformationGroupCustomRoute
  '/bookInformationGroup/detail': typeof BookInformationGroupDetailRoute
  '/bookInformationGroup/librarian': typeof BookInformationGroupLibrarianRoute
  '/bookInformationGroup/new': typeof BookInformationGroupNewRoute
  '/etc/courseList': typeof EtcCourseListRoute
  '/etc/courseRegistration': typeof EtcCourseRegistrationRoute
  '/etc/line': typeof EtcLineRoute
  '/etc/return': typeof EtcReturnRoute
  '/gallery/digitalGallery': typeof GalleryDigitalGalleryRoute
  '/informationGroup/event': typeof InformationGroupEventRoute
  '/informationGroup/facility': typeof InformationGroupFacilityRoute
  '/informationGroup/information': typeof InformationGroupInformationRoute
  '/informationGroup/living': typeof InformationGroupLivingRoute
  '/informationGroup/notice': typeof InformationGroupNoticeRoute
  '/informationGroup/promotion': typeof InformationGroupPromotionRoute
  '/informationGroup/welcomeMessage': typeof InformationGroupWelcomeMessageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookInformationGroup'
    | '/etc'
    | '/gallery'
    | '/informationGroup'
    | '/bookInformationGroup/best'
    | '/bookInformationGroup/bigdata'
    | '/bookInformationGroup/chart'
    | '/bookInformationGroup/custom'
    | '/bookInformationGroup/detail'
    | '/bookInformationGroup/librarian'
    | '/bookInformationGroup/new'
    | '/etc/courseList'
    | '/etc/courseRegistration'
    | '/etc/line'
    | '/etc/return'
    | '/gallery/digitalGallery'
    | '/informationGroup/event'
    | '/informationGroup/facility'
    | '/informationGroup/information'
    | '/informationGroup/living'
    | '/informationGroup/notice'
    | '/informationGroup/promotion'
    | '/informationGroup/welcomeMessage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookInformationGroup'
    | '/etc'
    | '/gallery'
    | '/informationGroup'
    | '/bookInformationGroup/best'
    | '/bookInformationGroup/bigdata'
    | '/bookInformationGroup/chart'
    | '/bookInformationGroup/custom'
    | '/bookInformationGroup/detail'
    | '/bookInformationGroup/librarian'
    | '/bookInformationGroup/new'
    | '/etc/courseList'
    | '/etc/courseRegistration'
    | '/etc/line'
    | '/etc/return'
    | '/gallery/digitalGallery'
    | '/informationGroup/event'
    | '/informationGroup/facility'
    | '/informationGroup/information'
    | '/informationGroup/living'
    | '/informationGroup/notice'
    | '/informationGroup/promotion'
    | '/informationGroup/welcomeMessage'
  id:
    | '__root__'
    | '/'
    | '/bookInformationGroup'
    | '/etc'
    | '/gallery'
    | '/informationGroup'
    | '/bookInformationGroup/best'
    | '/bookInformationGroup/bigdata'
    | '/bookInformationGroup/chart'
    | '/bookInformationGroup/custom'
    | '/bookInformationGroup/detail'
    | '/bookInformationGroup/librarian'
    | '/bookInformationGroup/new'
    | '/etc/courseList'
    | '/etc/courseRegistration'
    | '/etc/line'
    | '/etc/return'
    | '/gallery/digitalGallery'
    | '/informationGroup/event'
    | '/informationGroup/facility'
    | '/informationGroup/information'
    | '/informationGroup/living'
    | '/informationGroup/notice'
    | '/informationGroup/promotion'
    | '/informationGroup/welcomeMessage'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookInformationGroupRoute: typeof BookInformationGroupRouteWithChildren
  EtcRoute: typeof EtcRouteWithChildren
  GalleryRoute: typeof GalleryRouteWithChildren
  InformationGroupRoute: typeof InformationGroupRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookInformationGroupRoute: BookInformationGroupRouteWithChildren,
  EtcRoute: EtcRouteWithChildren,
  GalleryRoute: GalleryRouteWithChildren,
  InformationGroupRoute: InformationGroupRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bookInformationGroup",
        "/etc",
        "/gallery",
        "/informationGroup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bookInformationGroup": {
      "filePath": "bookInformationGroup.tsx",
      "children": [
        "/bookInformationGroup/best",
        "/bookInformationGroup/bigdata",
        "/bookInformationGroup/chart",
        "/bookInformationGroup/custom",
        "/bookInformationGroup/detail",
        "/bookInformationGroup/librarian",
        "/bookInformationGroup/new"
      ]
    },
    "/etc": {
      "filePath": "etc.tsx",
      "children": [
        "/etc/courseList",
        "/etc/courseRegistration",
        "/etc/line",
        "/etc/return"
      ]
    },
    "/gallery": {
      "filePath": "gallery.tsx",
      "children": [
        "/gallery/digitalGallery"
      ]
    },
    "/informationGroup": {
      "filePath": "informationGroup.tsx",
      "children": [
        "/informationGroup/event",
        "/informationGroup/facility",
        "/informationGroup/information",
        "/informationGroup/living",
        "/informationGroup/notice",
        "/informationGroup/promotion",
        "/informationGroup/welcomeMessage"
      ]
    },
    "/bookInformationGroup/best": {
      "filePath": "bookInformationGroup.best.tsx",
      "parent": "/bookInformationGroup"
    },
    "/bookInformationGroup/bigdata": {
      "filePath": "bookInformationGroup.bigdata.tsx",
      "parent": "/bookInformationGroup"
    },
    "/bookInformationGroup/chart": {
      "filePath": "bookInformationGroup.chart.tsx",
      "parent": "/bookInformationGroup"
    },
    "/bookInformationGroup/custom": {
      "filePath": "bookInformationGroup.custom.tsx",
      "parent": "/bookInformationGroup"
    },
    "/bookInformationGroup/detail": {
      "filePath": "bookInformationGroup.detail.tsx",
      "parent": "/bookInformationGroup"
    },
    "/bookInformationGroup/librarian": {
      "filePath": "bookInformationGroup.librarian.tsx",
      "parent": "/bookInformationGroup"
    },
    "/bookInformationGroup/new": {
      "filePath": "bookInformationGroup.new.tsx",
      "parent": "/bookInformationGroup"
    },
    "/etc/courseList": {
      "filePath": "etc.courseList.tsx",
      "parent": "/etc"
    },
    "/etc/courseRegistration": {
      "filePath": "etc.courseRegistration.tsx",
      "parent": "/etc"
    },
    "/etc/line": {
      "filePath": "etc.line.tsx",
      "parent": "/etc"
    },
    "/etc/return": {
      "filePath": "etc.return.tsx",
      "parent": "/etc"
    },
    "/gallery/digitalGallery": {
      "filePath": "gallery.digitalGallery.tsx",
      "parent": "/gallery"
    },
    "/informationGroup/event": {
      "filePath": "informationGroup.event.tsx",
      "parent": "/informationGroup"
    },
    "/informationGroup/facility": {
      "filePath": "informationGroup.facility.tsx",
      "parent": "/informationGroup"
    },
    "/informationGroup/information": {
      "filePath": "informationGroup.information.tsx",
      "parent": "/informationGroup"
    },
    "/informationGroup/living": {
      "filePath": "informationGroup.living.tsx",
      "parent": "/informationGroup"
    },
    "/informationGroup/notice": {
      "filePath": "informationGroup.notice.tsx",
      "parent": "/informationGroup"
    },
    "/informationGroup/promotion": {
      "filePath": "informationGroup.promotion.tsx",
      "parent": "/informationGroup"
    },
    "/informationGroup/welcomeMessage": {
      "filePath": "informationGroup.welcomeMessage.tsx",
      "parent": "/informationGroup"
    }
  }
}
ROUTE_MANIFEST_END */
